define([], function () {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint":
      "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams":
      "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice":
      "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook":
      "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    Time: "Time",
    Subject: "Title",
    SubjectMessage: "Title is required",
    Description: "Description",
    DescriptionMessage: "Description is required",
    Team: "Team",
    TeamMessage: "Team is required",
    TeamSelect: "--- Select a Team ---",
    StartDateTime: "Start DateTime",
    Date: "Date",
    EndDateTime: "End DateTime",
    Attendees: "Attendees",
    Save: "Save",
    Close: "Close",
    AllDay: "All Day",
    MeetingCreateEvent: "Create Online Meeting Event",
    MeetingViewEvent: "View Online Meeting Event",
    ConfirmDelete: "Are you sure you want to delete '{0}' event?",
    JoinMeeting: "Join the Meeting",
    Cancel: "Cancel",
    DeleteEvent: "Delete Event",
    ViewOutlook: "View in Outlook",
    Location: "Location",
    CreateEvent: "Create Event",
    FindNoTeam: "Cannot find the team",
    OnlineMeetings: "Online Meetings",
    Delete: "Delete",
    Confirmation: "Confirmation",
    ViewMeetings: "View Meetings",
    BrowserVideo: "Your browser does not support the video tag",
    NoRecordings: "No recordings found",
  };
});
